export interface ChatterboxVoice {
  id: string;
  name: string;
  description: string;
  url: string;
  gender: 'Male' | 'Female' | 'Neutral';
  disabled?: boolean;
}

export const chatterboxVoices: ChatterboxVoice[] = [
  {
    id: 'teen-boy',
    name: 'Teenage Boy',
    description: 'A standard teenage male voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614074/Vooboo/hiphop/wuszbvui0h9kz4pdklna.mp3',
    gender: 'Male',
  },
  {
    id: 'teen-girl',
    name: 'Teenage Girl',
    description: 'A standard teenage female voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614170/Vooboo/hiphop/ungogjlduzpttvrwzqnj.mp3',
    gender: 'Female',
  },
   {
    id: 'teen-girl-2',
    name: 'Teen Girl 2',
    description: 'Another variation of a teenage female voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614623/Vooboo/hiphop/hqvfo6l1jbocbgh1zgpp.mp3',
    gender: 'Female',
  },
  {
    id: 'little-boy',
    name: 'Little Boy',
    description: 'A young male child\'s voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614310/Vooboo/hiphop/twqtz9l2lwldcd44ifat.mp3',
    gender: 'Male',
  },
  {
    id: 'energetic-boy',
    name: 'Energetic Little Boy',
    description: 'An energetic young male child\'s voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614539/Vooboo/hiphop/m1w0uzxplt8gltxcxjmr.mp3',
    gender: 'Male',
  },
  {
    id: 'old-man',
    name: 'Old Man',
    description: 'An elderly male voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614400/Vooboo/hiphop/zbxfcl5c28qd3lala83n.mp3',
    gender: 'Male',
  },
    {
    id: 'old-man-2',
    name: 'Old Man 2',
    description: 'Another variation of an elderly male voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614817/Vooboo/hiphop/eq6smxxpx53rwqtejpen.mp3',
    gender: 'Male',
  },
  {
    id: 'old-woman',
    name: 'Old Woman',
    description: 'An elderly female voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614489/Vooboo/hiphop/hr5vmz4yplqlbhlpfzfq.mp3',
    gender: 'Female',
  },
  {
    id: 'narrator-male',
    name: 'Male Narrator',
    description: 'A clear male voice for narration.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614706/Vooboo/hiphop/grtbmnu7yr51zaoyylzj.mp3',
    gender: 'Male',
  },
  {
    id: 'male-deep',
    name: 'Deep Male Voice',
    description: 'A deep and resonant male voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614768/Vooboo/hiphop/sm48gsbrrrjnakmao7gu.mp3',
    gender: 'Male',
  },
  {
    id: 'female-standard',
    name: 'Female Voice',
    description: 'A standard adult female voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769614895/Vooboo/hiphop/ortxasmqri5zyn1rlqoe.mp3',
    gender: 'Female',
  },
  {
    id: 'toony-chidiya',
    name: 'Toony Chidiya (Cartoon Bird)',
    description: 'A high-pitched, cartoonish bird voice.',
    url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1769613889/Vooboo/hiphop/b4n5nrea3h7m7fcqxrqh.mp3',
    gender: 'Neutral',
  },
  { id: 'puck', name: 'Puck', description: 'A quirky, high-pitched male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1761300714/Vooboo/hiphop/bgphd9xnptzy89tplgia.wav', gender: 'Male' },
  { id: 'zephyr', name: 'Zephyr', description: 'A fast-paced, energetic female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865277/Vooboo/hiphop/wysvrsrse24g2sfhtqnl.wav', gender: 'Female' },
  { id: 'charon', name: 'Charon', description: 'A very deep, gravelly male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863124/Vooboo/hiphop/t8flesyrhth8qmwmpboa.wav', gender: 'Male' },
  { id: 'fenrir', name: 'Fenrir', description: 'An aggressive, powerful male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863309/Vooboo/hiphop/j6yav9hejw5pa3rtc2xi.wav', gender: 'Male' },
  { id: 'leda', name: 'Leda', description: 'An older, grandmotherly voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865172/Vooboo/hiphop/q1y0zuokalgnhajftzoz.wav', gender: 'Female' },
  { id: 'aoede', name: 'Aoede', description: 'A light, airy female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759030170/Vooboo/hiphop/gk1rpyap35j3simthh1r.wav', gender: 'Female' },
  { id: 'orus', name: 'Orus', description: 'A heroic, booming male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759029922/Vooboo/hiphop/f2rvf15avbcavcbw5bm8.wav', gender: 'Male' },
  { id: 'autonoe', name: 'Autonoe', description: 'A professional, clear female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759030313/Vooboo/hiphop/clodgo399lorrobg7v70.wav', gender: 'Female' },
  { id: 'callirrhoe', name: 'Callirrhoe', description: 'A warm, motherly female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759030170/Vooboo/hiphop/gk1rpyap35j3simthh1r.wav', gender: 'Female' },
  { id: 'enceladus', name: 'Enceladus', description: 'A dark, ominous male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863168/Vooboo/hiphop/yfg6lhpeb6xwv86r8tcs.wav', gender: 'Male' },
  { id: 'achird', name: 'Achird', description: 'A standard, middle-aged male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760862758/Vooboo/hiphop/v3kmmji1lcw5v5n4rrf5.wav', gender: 'Male' },
  { id: 'algenib', name: 'Algenib', description: 'A deep, authoritative male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760862842/Vooboo/hiphop/usgktihmagapvmuyqxul.wav', gender: 'Male' },
  { id: 'algieba', name: 'Algieba', description: 'A friendly, youthful male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760862908/Vooboo/hiphop/tnyc92h4ueltu2gm4xuy.wav', gender: 'Male' },
  { id: 'alnilam', name: 'Alnilam', description: 'A slightly older, wise male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863004/Vooboo/hiphop/zxxhumodxpstvxvbro28.wav', gender: 'Male' },
  { id: 'iapetus', name: 'Iapetus', description: 'An older, grandfatherly voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863349/Vooboo/hiphop/tkzw9gikqijcnp0fshov.wav', gender: 'Male' },
  { id: 'rasalgethi', name: 'Rasalgethi', description: 'A standard male narrator voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863945/Vooboo/hiphop/a9k2on5sgoxr6a9xmmul.wav', gender: 'Male' },
  { id: 'sadachbia', name: 'Sadachbia', description: 'A calm and soothing male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760864002/Vooboo/hiphop/wbqrztniuw8bl86ofrhz.wav', gender: 'Male' },
  { id: 'achernar', name: 'Achernar', description: 'A calm, mature female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760864918/Vooboo/hiphop/w1cwzd1ktuza3qmsaadt.wav', gender: 'Female' },
  { id: 'despina', name: 'Despina', description: 'A sharp, confident female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865052/Vooboo/hiphop/drz2tpmc2yjhpoxpwy1b.wav', gender: 'Female' },
  { id: 'erinome', name: 'Erinome', description: 'A soft-spoken, gentle female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865078/Vooboo/hiphop/pw1nsv16qeqynomvf9rb.wav', gender: 'Female' },
  { id: 'gacrux', name: 'Gacrux', description: 'A standard, middle-aged female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865099/Vooboo/hiphop/s31wivpghju2tc4w30om.wav', gender: 'Female' },
  { id: 'laomedeia', name: 'Laomedeia', description: 'A mysterious, alluring female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865146/Vooboo/hiphop/mlcc9awcvdfkxc9vsrxl.wav', gender: 'Female' },
  { id: 'kore', name: 'Kore', description: 'A youthful, energetic female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865125/Vooboo/hiphop/jfpj35goyst0pdb1jdro.wav', gender: 'Female' },
  { id: 'pulcherrima', name: 'Pulcherrima', description: 'A beautiful, smooth female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865192/Vooboo/hiphop/r7nqe5uf6bvvdjc9uey7.wav', gender: 'Female', disabled: true },
  { id: 'vindemiatrix', name: 'Vindemiatrix', description: 'A powerful, commanding female voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865251/Vooboo/hiphop/dri5w7gy4oju2i9frsfd.wav', gender: 'Female' },
  { id: 'sulafat', name: 'Sulafat', description: 'A standard female narrator voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865219/Vooboo/hiphop/s2jtmje08hylftrgwn1j.wav', gender: 'Female' },
  { id: 'schedar', name: 'Schedar', description: 'A neutral, balanced male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872188/Vooboo/hiphop/dyafc8yalilvreylkivt.wav', gender: 'Male' },
  { id: 'sadaltager', name: 'Sadaltager', description: 'A gruff, tough male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872060/Vooboo/hiphop/tamx43cszzail8ziphx2.wav', gender: 'Male' },
  { id: 'zubenelgenubi', name: 'Zubenelgenubi', description: 'An eccentric, older male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872248/Vooboo/hiphop/bymzup8fah6lf5zq8t4z.wav', gender: 'Male' },
  { id: 'umbriel', name: 'Umbriel', description: 'A sinister, whispering male voice.', url: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872218/Vooboo/hiphop/ecieaqck02y1og2rtkes.wav', gender: 'Male' },
];
