
export const voices = [
    { id: 'achernar', name: 'Achernar', gender: 'Female', description: 'A calm, mature male voice. Good for narrators or thoughtful characters.', tags: ['calm', 'mature', 'neutral'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760864918/Vooboo/hiphop/w1cwzd1ktuza3qmsaadt.wav' },
    { id: 'achird', name: 'Achird', gender: 'Male', description: 'A standard, middle-aged male voice. Versatile for many roles.', tags: ['standard', 'middle-aged', 'neutral'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760862758/Vooboo/hiphop/v3kmmji1lcw5v5n4rrf5.wav' },
    { id: 'algenib', name: 'Algenib', gender: 'Male', description: 'A deep, authoritative male voice. Excellent for villains or serious narration.', tags: ['deep', 'authoritative', 'serious'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760862842/Vooboo/hiphop/usgktihmagapvmuyqxul.wav' },
    { id: 'algieba', name: 'Algieba', gender: 'Male', description: 'A friendly, youthful male voice. Good for protagonists or friendly characters.', tags: ['friendly', 'youthful', 'energetic'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760862908/Vooboo/hiphop/tnyc92h4ueltu2gm4xuy.wav' },
    { id: 'alnilam', name: 'Alnilam', gender: 'Male', description: 'A slightly older, wise male voice. Suitable for mentors or fatherly figures.', tags: ['wise', 'older', 'calm'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863004/Vooboo/hiphop/zxxhumodxpstvxvbro28.wav' },
    { id: 'aoede', name: 'Aoede', gender: 'Female', description: 'A light, airy female voice. Good for young or cheerful characters.', tags: ['light', 'youthful', 'happy'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759030170/Vooboo/hiphop/gk1rpyap35j3simthh1r.wav' },
    { id: 'autonoe', name: 'Autonoe', gender: 'Female', description: 'A professional, clear female voice. Great for corporate or instructional content.', tags: ['professional', 'clear', 'neutral'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759030313/Vooboo/hiphop/clodgo399lorrobg7v70.wav' },
    { id: 'callirrhoe', name: 'Callirrhoe', gender: 'Female', description: 'A warm, motherly female voice. Perfect for caring or gentle characters.', tags: ['warm', 'motherly', 'calm'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759030170/Vooboo/hiphop/gk1rpyap35j3simthh1r.wav' },
    { id: 'charon', name: 'Charon', gender: 'Male', description: 'A very deep, gravelly male voice. Ideal for monsters, demons, or intimidating figures.', tags: ['deep', 'gravelly', 'scary'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863124/Vooboo/hiphop/t8flesyrhth8qmwmpboa.wav' },
    { id: 'despina', name: 'Despina', gender: 'Female', description: 'A sharp, confident female voice. Good for leaders or assertive characters.', tags: ['confident', 'assertive', 'clear'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865052/Vooboo/hiphop/drz2tpmc2yjhpoxpwy1b.wav' },
    { id: 'enceladus', name: 'Enceladus', gender: 'Male', description: 'A dark, ominous male voice. Perfect for horror narration or villains.', tags: ['dark', 'ominous', 'scary', 'deep'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863168/Vooboo/hiphop/yfg6lhpeb6xwv86r8tcs.wav' },
    { id: 'erinome', name: 'Erinome', gender: 'Female', description: 'A soft-spoken, gentle female voice. Good for emotional or shy characters.', tags: ['soft', 'gentle', 'sad'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865078/Vooboo/hiphop/pw1nsv16qeqynomvf9rb.wav' },
    { id: 'fenrir', name: 'Fenrir', gender: 'Male', description: 'An aggressive, powerful male voice. Suitable for action heroes or angry characters.', tags: ['aggressive', 'powerful', 'angry'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863309/Vooboo/hiphop/j6yav9hejw5pa3rtc2xi.wav' },
    { id: 'gacrux', name: 'Gacrux', gender: 'Female', description: 'A standard, middle-aged male voice. A reliable choice for a variety of roles.', tags: ['standard', 'middle-aged', 'neutral'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865099/Vooboo/hiphop/s31wivpghju2tc4w30om.wav' },
    { id: 'iapetus', name: 'Iapetus', gender: 'Male', description: 'An older, grandfatherly voice. Wise and calming.', tags: ['older', 'wise', 'grandfatherly'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863349/Vooboo/hiphop/tkzw9gikqijcnp0fshov.wav' },
    { id: 'kore', name: 'Kore', gender: 'Female', description: 'A youthful, energetic female voice. Ideal for teenage or young adult characters.', tags: ['youthful', 'energetic', 'happy'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865125/Vooboo/hiphop/jfpj35goyst0pdb1jdro.wav' },
    { id: 'laomedeia', name: 'Laomedeia', gender: 'Female', description: 'A mysterious, alluring female voice. Good for femme fatales or enigmatic characters.', tags: ['mysterious', 'alluring', 'sultry'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865146/Vooboo/hiphop/mlcc9awcvdfkxc9vsrxl.wav' },
    { id: 'leda', name: 'Leda', gender: 'Female', description: 'An older, grandmotherly voice. Kind and warm.', tags: ['older', 'warm', 'grandmotherly'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865172/Vooboo/hiphop/q1y0zuokalgnhajftzoz.wav' },
    { id: 'orus', name: 'Orus', gender: 'Male', description: 'A heroic, booming male voice. Great for epic narration or heroes.', tags: ['heroic', 'booming', 'powerful'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1759029922/Vooboo/hiphop/f2rvf15avbcavcbw5bm8.wav' },
    { id: 'pulcherrima', name: 'Pulcherrima', gender: 'Female', description: 'A beautiful, smooth female voice. Ideal for romantic leads or pleasant narration.', tags: ['smooth', 'pleasant', 'calm'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865192/Vooboo/hiphop/r7nqe5uf6bvvdjc9uey7.wav', disabled: true },
    { id: 'puck', name: 'Puck', gender: 'Male', description: 'A quirky, high-pitched male voice. Good for comic relief or unique characters.', tags: ['quirky', 'high-pitched', 'comedic'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1761300714/Vooboo/hiphop/bgphd9xnptzy89tplgia.wav' },
    { id: 'rasalgethi', name: 'Rasalgethi', gender: 'Male', description: 'A standard male narrator voice. Clear and professional.', tags: ['narrator', 'clear', 'professional'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760863945/Vooboo/hiphop/a9k2on5sgoxr6a9xmmul.wav' },
    { id: 'sadachbia', name: 'Sadachbia', gender: 'Male', description: 'A calm and soothing male voice. Good for meditation or relaxation content.', tags: ['calm', 'soothing', 'gentle'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760864002/Vooboo/hiphop/wbqrztniuw8bl86ofrhz.wav' },
    { id: 'sadaltager', name: 'Sadaltager', gender: 'Male', description: 'A gruff, tough male voice. Suitable for soldiers or rugged characters.', tags: ['gruff', 'tough', 'aggressive'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872060/Vooboo/hiphop/tamx43cszzail8ziphx2.wav' },
    { id: 'schedar', name: 'Schedar', gender: 'Male', description: 'A neutral, balanced male voice. Highly versatile.', tags: ['neutral', 'versatile', 'standard'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872188/Vooboo/hiphop/dyafc8yalilvreylkivt.wav' },
    { id: 'sulafat', name: 'Sulafat', gender: 'Female', description: 'A standard female narrator voice. Clear, professional, and pleasant.', tags: ['narrator', 'clear', 'professional', 'pleasant'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865219/Vooboo/hiphop/s2jtmje08hylftrgwn1j.wav' },
    { id: 'umbriel', name: 'Umbriel', gender: 'Male', description: 'A sinister, whispering male voice. Excellent for suspense or horror.', tags: ['sinister', 'whispering', 'scary'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872218/Vooboo/hiphop/ecieaqck02y1og2rtkes.wav' },
    { id: 'vindemiatrix', name: 'Vindemiatrix', gender: 'Female', description: 'A powerful, commanding female voice. Suitable for queens or leaders.', tags: ['powerful', 'commanding', 'authoritative'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865251/Vooboo/hiphop/dri5w7gy4oju2i9frsfd.wav' },
    { id: 'zephyr', name: 'Zephyr', gender: 'Female', description: 'A fast-paced, energetic female voice. Good for commercials or excited characters.', tags: ['energetic', 'fast-paced', 'excited'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760865277/Vooboo/hiphop/wysvrsrse24g2sfhtqnl.wav' },
    { id: 'zubenelgenubi', name: 'Zubenelgenubi', gender: 'Male', description: 'An eccentric, older male voice. Good for scientists or quirky old men.', tags: ['eccentric', 'older', 'quirky'], demoUrl: 'https://res.cloudinary.com/dzftuktit/video/upload/v1760872248/Vooboo/hiphop/bymzup8fah6lf5zq8t4z.wav' },
];

export const emotions = [
    "Neutral", "Happy", "Sad", "Angry", "Surprised", "Fearful", "Disgusted", "Excited", "Anxious", "Calm"
];

