
export const voices = [
    { id: 'achernar', name: 'Achernar', gender: 'Female', description: 'A calm, mature male voice. Good for narrators or thoughtful characters.', tags: ['calm', 'mature', 'neutral'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/achernar.wav' },
    { id: 'achird', name: 'Achird', gender: 'Male', description: 'A standard, middle-aged male voice. Versatile for many roles.', tags: ['standard', 'middle-aged', 'neutral'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/achird.wav' },
    { id: 'algenib', name: 'Algenib', gender: 'Male', description: 'A deep, authoritative male voice. Excellent for villains or serious narration.', tags: ['deep', 'authoritative', 'serious'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/algenib.wav' },
    { id: 'algieba', name: 'Algieba', gender: 'Male', description: 'A friendly, youthful male voice. Good for protagonists or friendly characters.', tags: ['friendly', 'youthful', 'energetic'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/algieba.wav' },
    { id: 'alnilam', name: 'Alnilam', gender: 'Male', description: 'A slightly older, wise male voice. Suitable for mentors or fatherly figures.', tags: ['wise', 'older', 'calm'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/alnilam.wav' },
    { id: 'aoede', name: 'Aoede', gender: 'Female', description: 'A light, airy female voice. Good for young or cheerful characters.', tags: ['light', 'youthful', 'happy'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/aoede.wav' },
    { id: 'autonoe', name: 'Autonoe', gender: 'Female', description: 'A professional, clear female voice. Great for corporate or instructional content.', tags: ['professional', 'clear', 'neutral'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/autonoe.wav' },
    { id: 'callirrhoe', name: 'Callirrhoe', gender: 'Female', description: 'A warm, motherly female voice. Perfect for caring or gentle characters.', tags: ['warm', 'motherly', 'calm'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/callirrhoe.wav' },
    { id: 'charon', name: 'Charon', gender: 'Male', description: 'A very deep, gravelly male voice. Ideal for monsters, demons, or intimidating figures.', tags: ['deep', 'gravelly', 'scary'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/charon.wav' },
    { id: 'despina', name: 'Despina', gender: 'Female', description: 'A sharp, confident female voice. Good for leaders or assertive characters.', tags: ['confident', 'assertive', 'clear'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/despina.wav' },
    { id: 'enceladus', name: 'Enceladus', gender: 'Male', description: 'A dark, ominous male voice. Perfect for horror narration or villains.', tags: ['dark', 'ominous', 'scary', 'deep'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/enceladus.wav' },
    { id: 'erinome', name: 'Erinome', gender: 'Female', description: 'A soft-spoken, gentle female voice. Good for emotional or shy characters.', tags: ['soft', 'gentle', 'sad'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/erinome.wav' },
    { id: 'fenrir', name: 'Fenrir', gender: 'Male', description: 'An aggressive, powerful male voice. Suitable for action heroes or angry characters.', tags: ['aggressive', 'powerful', 'angry'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/fenrir.wav' },
    { id: 'gacrux', name: 'Gacrux', gender: 'Female', description: 'A standard, middle-aged male voice. A reliable choice for a variety of roles.', tags: ['standard', 'middle-aged', 'neutral'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/gacrux.wav' },
    { id: 'iapetus', name: 'Iapetus', gender: 'Male', description: 'An older, grandfatherly voice. Wise and calming.', tags: ['older', 'wise', 'grandfatherly'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/iapetus.wav' },
    { id: 'kore', name: 'Kore', gender: 'Female', description: 'A youthful, energetic female voice. Ideal for teenage or young adult characters.', tags: ['youthful', 'energetic', 'happy'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/kore.wav' },
    { id: 'laomedeia', name: 'Laomedeia', gender: 'Female', description: 'A mysterious, alluring female voice. Good for femme fatales or enigmatic characters.', tags: ['mysterious', 'alluring', 'sultry'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/laomedeia.wav' },
    { id: 'leda', name: 'Leda', gender: 'Female', description: 'An older, grandmotherly voice. Kind and warm.', tags: ['older', 'warm', 'grandmotherly'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/leda.wav' },
    { id: 'orus', name: 'Orus', gender: 'Male', description: 'A heroic, booming male voice. Great for epic narration or heroes.', tags: ['heroic', 'booming', 'powerful'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/orus.wav' },
    { id: 'pulcherrima', name: 'Pulcherrima', gender: 'Female', description: 'A beautiful, smooth female voice. Ideal for romantic leads or pleasant narration.', tags: ['smooth', 'pleasant', 'calm'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/pulcherrima.wav', disabled: true },
    { id: 'puck', name: 'Puck', gender: 'Male', description: 'A quirky, high-pitched male voice. Good for comic relief or unique characters.', tags: ['quirky', 'high-pitched', 'comedic'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/puck.wav' },
    { id: 'rasalgethi', name: 'Rasalgethi', gender: 'Male', description: 'A standard male narrator voice. Clear and professional.', tags: ['narrator', 'clear', 'professional'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/rasalgethi.wav' },
    { id: 'sadachbia', name: 'Sadachbia', gender: 'Male', description: 'A calm and soothing male voice. Good for meditation or relaxation content.', tags: ['calm', 'soothing', 'gentle'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/sadachbia.wav' },
    { id: 'sadaltager', name: 'Sadaltager', gender: 'Male', description: 'A gruff, tough male voice. Suitable for soldiers or rugged characters.', tags: ['gruff', 'tough', 'aggressive'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/sadaltager.wav' },
    { id: 'schedar', name: 'Schedar', gender: 'Male', description: 'A neutral, balanced male voice. Highly versatile.', tags: ['neutral', 'versatile', 'standard'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/schedar.wav' },
    { id: 'sulafat', name: 'Sulafat', gender: 'Female', description: 'A standard female narrator voice. Clear, professional, and pleasant.', tags: ['narrator', 'clear', 'professional', 'pleasant'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/sulafat.wav' },
    { id: 'umbriel', name: 'Umbriel', gender: 'Male', description: 'A sinister, whispering male voice. Excellent for suspense or horror.', tags: ['sinister', 'whispering', 'scary'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/umbriel.wav' },
    { id: 'vindemiatrix', name: 'Vindemiatrix', gender: 'Female', description: 'A powerful, commanding female voice. Suitable for queens or leaders.', tags: ['powerful', 'commanding', 'authoritative'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/vindemiatrix.wav' },
    { id: 'zephyr', name: 'Zephyr', gender: 'Female', description: 'A fast-paced, energetic female voice. Good for commercials or excited characters.', tags: ['energetic', 'fast-paced', 'excited'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/zephyr.wav' },
    { id: 'zubenelgenubi', name: 'Zubenelgenubi', gender: 'Male', description: 'An eccentric, older male voice. Good for scientists or quirky old men.', tags: ['eccentric', 'older', 'quirky'], demoUrl: 'https://storage.googleapis.com/12labspublic/voices/zubenelgenubi.wav' },
];

export const emotions = [
    "Neutral", "Happy", "Sad", "Angry", "Surprised", "Fearful", "Disgusted", "Excited", "Anxious", "Calm"
];

